#!/bin/sh

set -e

APP=ubuntu-tweak

VERSION=`cd ~/Sources/ubuntu-tweak && python -c 'import ubuntutweak;print ubuntutweak.__version__'`

if [ ! -n "$1" ];then
    echo "Please enter the codename to build"
    exit 1
fi

release-build $APP $VERSION $1
